# Site settings
title: Vinicius Xaxá
description: >
  Alguns pensamentos, ideias ou loucuras minhas. A última principalmente.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://viniciusxaxa.com.br" # the base hostname & protocol for your site

author:
  fullname: Vinicius Xaxá
  #googleplus: https://www.google.com/
  github: xaxa
  twitter: xaxa
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
timezone: America/Sao_Paulo