# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vinicius Xaxá
email: vinicius.xaxa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Alguns pensamentos, ideias ou loucuras minhas. A última principalmente.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://viniciusxaxa.com.br" # the base hostname & protocol for your site
twitter_username: xaxa
github_username:  xaxa

# Build settings
markdown: kramdown

timezone: America/Sao_Paulo
